# Generated by Django 5.1.4 on 2026-06-08 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/images/')),
                ('category', models.CharField(choices=[('prelims', 'Prelims'), ('mains', 'Mains'), ('current_affairs', 'Current Affairs'), ('editorial', 'Editorial Analysis')], db_index=True, default='mains', max_length=20)),
                ('gs_paper', models.CharField(blank=True, choices=[('gs1', 'GS Paper 1'), ('gs2', 'GS Paper 2'), ('gs3', 'GS Paper 3'), ('gs4', 'GS Paper 4 (Ethics)'), ('essay', 'Essay')], db_index=True, max_length=10)),
                ('micro_topics', models.JSONField(blank=True, default=list, help_text='AI-generated micro-topic tags from UPSC syllabus.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_premium', models.BooleanField(default=False, help_text='If True, content is restricted to active subscribers.')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('quiz_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='blog.blogpost')),
            ],
            options={
                'db_table': 'mcq_questions',
                'ordering': ['-quiz_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', 'is_published'], name='blog_posts_categor_325b52_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['gs_paper', 'is_published'], name='blog_posts_gs_pape_1cb93a_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_at'], name='blog_posts_publish_12812e_idx'),
        ),
    ]
